shortened_names:
  # will be used for labeling files, no spaces
  # first is the target species (S_cer here)
  # Must be unique and 5 characters long
  GCF_000146045.2: "S_cer"
  S_par          : "S_par"
  S_mik          : "S_mik"
  S_kud          : "S_kud"
  S_bay          : "S_bay"
  GCF_000237345.1: "S_cas"
  K_wal          : "K_wal"
  GCF_000091025.4: "A_gos"
  GCF_000002515.2: "K_lac"
  GCA_000149205.2: "A_nid"
  GCA_000002945.2: "S_pom"
  GCA_000002525.1: "Y_lip"


paths:
  faa: "fastas/{species}.faa"

  # for determining distances
  busco: 'eukaryota_odb10'
  busco_hmm: 'eukaryota_odb10/hmms/{id}.hmm'
  hmm_matches: 'matches/{id}.txt'
  busco_faa: 'busco_genes/{id}.faa'
  muscle_alignment: 'muscle/{id}.afa'
  merged_afa: 'merged.afa'
  distances: 'distances.txt'

  # for determining bitscores
  blast_db: "blast_dbs/{species}.faa"
  # list of genes, one per line.  Remove to target all genes in target species
  target_genes: "targets.txt"

  target_fasta: "scoring/targets/{species}.faa"
  reciprocal_genes: "scoring/targets/{species}_genes.txt"
  blast_scores: "scoring/blast/{query}/{database}.txt"
  bit_scores: 'bit_scores.txt'

urls:
  # link to download each species, keys must match shorted names, can be gzipped
  faa:
    # keys must match shortened names
    GCF_000146045.2: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_protein.faa.gz"
    GCF_000237345.1: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/237/345/GCF_000237345.1_ASM23734v1/GCF_000237345.1_ASM23734v1_protein.faa.gz"
    GCF_000091025.4: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/091/025/GCF_000091025.4_ASM9102v4/GCF_000091025.4_ASM9102v4_protein.faa.gz"
    GCF_000002515.2: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/515/GCF_000002515.2_ASM251v1/GCF_000002515.2_ASM251v1_protein.faa.gz"
    S_par          : "http://www.saccharomycessensustricto.org/current/Spar/Spar.aa"
    S_mik          : "http://www.saccharomycessensustricto.org/current/Smik/Smik.aa"
    S_kud          : "http://www.saccharomycessensustricto.org/current/Skud/Skud.aa"
    S_bay          : "http://www.saccharomycessensustricto.org/current/Sbay/Sbay.aa"
    # K_wal          : "https://static-content.springer.com/esm/art%3A10.1038%2Fnature02424/MediaObjects/41586_2004_BFnature02424_MOESM2_ESM.zip"  # manually downloaded
    GCA_000149205.2: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/149/205/GCA_000149205.2_ASM14920v2/GCA_000149205.2_ASM14920v2_protein.faa.gz"
    GCA_000002945.2: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/002/945/GCA_000002945.2_ASM294v2/GCA_000002945.2_ASM294v2_protein.faa.gz"
    GCA_000002525.1: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/002/525/GCA_000002525.1_ASM252v1/GCA_000002525.1_ASM252v1_protein.faa.gz"

  busco: "https://busco-data.ezlab.org/v4/data/lineages/eukaryota_odb10.2020-09-10.tar.gz"

hmmer_e_val: 0.01
blast_e_val: 0.001
