---
# base directory for data and results
workdir: '/scratch/gpfs/tcomi/absense'

# analysis parameters
# e value threshold for matching busco genes to faa entries
hmmer_e_val: 0.01
# e value threshold for detecting reciprical matches between species
blast_e_val: 0.001

# Parameters for providing confidence on genetic distance estimate
# fast
protdist_merged_genes: 30  # how many busco genes to consider per replicate
protdist_replicates: 30    # how many replicates to perform

# precise
# protdist_merged_genes: 100
# protdist_replicates: 100

species:
  # will be used for labeling files, no spaces, must be unique and 5 characters long
  S_cer:
    target: true  # only one target may be set
    # urls can point to gzipped or non-compressed files
    url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_protein.faa.gz"
  S_par:
    url: "http://www.saccharomycessensustricto.org/current/Spar/Spar.aa"
  S_mik:
    url: "http://www.saccharomycessensustricto.org/current/Smik/Smik.aa"
  S_kud:
    url: "http://www.saccharomycessensustricto.org/current/Skud/Skud.aa"
  S_bay:
    url: "http://www.saccharomycessensustricto.org/current/Sbay/Sbay.aa"
  S_cas:
    # genback or refseq accessions will be downloaded with datasets from ncbi
    accession: GCF_000237345.1
  K_wal:
    # local files will be soft linked, must be uncompressed
    file: "/scratch/gpfs/tcomi/absense/fastas/K_wal.faa"
  A_gos:
    accession: GCF_000091025.4
  K_lac:
    accession: GCF_000002515.2
  A_nid:
    accession: GCA_000149205.2
  S_pom:
    accession: GCA_000002945.2
  Y_lip:
    accession: GCA_000002525.1
    # if more than one access method is provided, the following priority is used:
    # local file copy
    # download with datasets
    # download from url
